
---
version: '1'

# App (Project) name
name: Fx-Gigy-Test

# App description
description: GitHub API Test Sample

# license
licenses:
  - APACHE LICENSE, VERSION 2.

# App environments
environments:
  - name: gigy
    baseUrl: http://localhost:8000/gigy
    # app access credentials
    auths:
      - name: Default
        authType: OAuth_2_0
        username: peter@example.com
        password: password
        clientId: gigy
        clientSecret: secret
        id: gigy
        accessTokenUri: http://localhost:8000/gigy/oauth/token
        #userAuthorizationUri: http://localhost:8000/gigy/oauth/token
        #clientAuthenticationScheme: form
        #authorizationScheme: form
        scope: read,write
        grantType: password

# Job profiles
jobs:
  - name: gigy
    environment: gigy
    tags:
      - V1
    regions: FxLabs/US_WEST_1
    #cron: '0 30 * ? * *'
    #issueTracker: FxLabs/Fx-GitHub-Test
